// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2
// Source: trend.proto

package server

import (
	"context"

	"github.com/hiepnv/crawl-ecomerce-golang/cmd/trend-service/internal/logic"
	"github.com/hiepnv/crawl-ecomerce-golang/cmd/trend-service/internal/svc"
	"github.com/hiepnv/crawl-ecomerce-golang/cmd/trend-service/trend"
)

type TrendServiceServer struct {
	svcCtx *svc.ServiceContext
	trend.UnimplementedTrendServiceServer
}

func NewTrendServiceServer(svcCtx *svc.ServiceContext) *TrendServiceServer {
	return &TrendServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *TrendServiceServer) GetTrendJob(ctx context.Context, in *trend.GetTrendJobRequest) (*trend.GetTrendJobResponse, error) {
	l := logic.NewGetTrendJobLogic(ctx, s.svcCtx)
	return l.GetTrendJob(in)
}
