// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v5.27.3
// source: fbads.proto

package fbads

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetFbAdsJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFbAdsJobRequest) Reset() {
	*x = GetFbAdsJobRequest{}
	mi := &file_fbads_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFbAdsJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFbAdsJobRequest) ProtoMessage() {}

func (x *GetFbAdsJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fbads_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFbAdsJobRequest.ProtoReflect.Descriptor instead.
func (*GetFbAdsJobRequest) Descriptor() ([]byte, []int) {
	return file_fbads_proto_rawDescGZIP(), []int{0}
}

func (x *GetFbAdsJobRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type GetFbAdsJobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	AdCount       int32                  `protobuf:"varint,2,opt,name=ad_count,json=adCount,proto3" json:"ad_count,omitempty"`
	AiOutput      string                 `protobuf:"bytes,3,opt,name=ai_output,json=aiOutput,proto3" json:"ai_output,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFbAdsJobResponse) Reset() {
	*x = GetFbAdsJobResponse{}
	mi := &file_fbads_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFbAdsJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFbAdsJobResponse) ProtoMessage() {}

func (x *GetFbAdsJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fbads_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFbAdsJobResponse.ProtoReflect.Descriptor instead.
func (*GetFbAdsJobResponse) Descriptor() ([]byte, []int) {
	return file_fbads_proto_rawDescGZIP(), []int{1}
}

func (x *GetFbAdsJobResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetFbAdsJobResponse) GetAdCount() int32 {
	if x != nil {
		return x.AdCount
	}
	return 0
}

func (x *GetFbAdsJobResponse) GetAiOutput() string {
	if x != nil {
		return x.AiOutput
	}
	return ""
}

var File_fbads_proto protoreflect.FileDescriptor

const file_fbads_proto_rawDesc = "" +
	"\n" +
	"\vfbads.proto\x12\x05fbads\"+\n" +
	"\x12GetFbAdsJobRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\"e\n" +
	"\x13GetFbAdsJobResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x19\n" +
	"\bad_count\x18\x02 \x01(\x05R\aadCount\x12\x1b\n" +
	"\tai_output\x18\x03 \x01(\tR\baiOutput2T\n" +
	"\fFbAdsService\x12D\n" +
	"\vGetFbAdsJob\x12\x19.fbads.GetFbAdsJobRequest\x1a\x1a.fbads.GetFbAdsJobResponseB\tZ\a./fbadsb\x06proto3"

var (
	file_fbads_proto_rawDescOnce sync.Once
	file_fbads_proto_rawDescData []byte
)

func file_fbads_proto_rawDescGZIP() []byte {
	file_fbads_proto_rawDescOnce.Do(func() {
		file_fbads_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_fbads_proto_rawDesc), len(file_fbads_proto_rawDesc)))
	})
	return file_fbads_proto_rawDescData
}

var file_fbads_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_fbads_proto_goTypes = []any{
	(*GetFbAdsJobRequest)(nil),  // 0: fbads.GetFbAdsJobRequest
	(*GetFbAdsJobResponse)(nil), // 1: fbads.GetFbAdsJobResponse
}
var file_fbads_proto_depIdxs = []int32{
	0, // 0: fbads.FbAdsService.GetFbAdsJob:input_type -> fbads.GetFbAdsJobRequest
	1, // 1: fbads.FbAdsService.GetFbAdsJob:output_type -> fbads.GetFbAdsJobResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_fbads_proto_init() }
func file_fbads_proto_init() {
	if File_fbads_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_fbads_proto_rawDesc), len(file_fbads_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_fbads_proto_goTypes,
		DependencyIndexes: file_fbads_proto_depIdxs,
		MessageInfos:      file_fbads_proto_msgTypes,
	}.Build()
	File_fbads_proto = out.File
	file_fbads_proto_goTypes = nil
	file_fbads_proto_depIdxs = nil
}
