// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.27.3
// source: fbads.proto

package fbads

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FbAdsService_GetFbAdsJob_FullMethodName = "/fbads.FbAdsService/GetFbAdsJob"
)

// FbAdsServiceClient is the client API for FbAdsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FbAdsServiceClient interface {
	GetFbAdsJob(ctx context.Context, in *GetFbAdsJobRequest, opts ...grpc.CallOption) (*GetFbAdsJobResponse, error)
}

type fbAdsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFbAdsServiceClient(cc grpc.ClientConnInterface) FbAdsServiceClient {
	return &fbAdsServiceClient{cc}
}

func (c *fbAdsServiceClient) GetFbAdsJob(ctx context.Context, in *GetFbAdsJobRequest, opts ...grpc.CallOption) (*GetFbAdsJobResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetFbAdsJobResponse)
	err := c.cc.Invoke(ctx, FbAdsService_GetFbAdsJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FbAdsServiceServer is the server API for FbAdsService service.
// All implementations must embed UnimplementedFbAdsServiceServer
// for forward compatibility.
type FbAdsServiceServer interface {
	GetFbAdsJob(context.Context, *GetFbAdsJobRequest) (*GetFbAdsJobResponse, error)
	mustEmbedUnimplementedFbAdsServiceServer()
}

// UnimplementedFbAdsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFbAdsServiceServer struct{}

func (UnimplementedFbAdsServiceServer) GetFbAdsJob(context.Context, *GetFbAdsJobRequest) (*GetFbAdsJobResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFbAdsJob not implemented")
}
func (UnimplementedFbAdsServiceServer) mustEmbedUnimplementedFbAdsServiceServer() {}
func (UnimplementedFbAdsServiceServer) testEmbeddedByValue()                      {}

// UnsafeFbAdsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FbAdsServiceServer will
// result in compilation errors.
type UnsafeFbAdsServiceServer interface {
	mustEmbedUnimplementedFbAdsServiceServer()
}

func RegisterFbAdsServiceServer(s grpc.ServiceRegistrar, srv FbAdsServiceServer) {
	// If the following call panics, it indicates UnimplementedFbAdsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FbAdsService_ServiceDesc, srv)
}

func _FbAdsService_GetFbAdsJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFbAdsJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FbAdsServiceServer).GetFbAdsJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FbAdsService_GetFbAdsJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FbAdsServiceServer).GetFbAdsJob(ctx, req.(*GetFbAdsJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FbAdsService_ServiceDesc is the grpc.ServiceDesc for FbAdsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FbAdsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "fbads.FbAdsService",
	HandlerType: (*FbAdsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetFbAdsJob",
			Handler:    _FbAdsService_GetFbAdsJob_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "fbads.proto",
}
