// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2
// Source: fbads.proto

package fbadsservice

import (
	"context"

	"github.com/hiepnv/crawl-ecomerce-golang/cmd/fb-ads-service/fbads"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	GetFbAdsJobRequest  = fbads.GetFbAdsJobRequest
	GetFbAdsJobResponse = fbads.GetFbAdsJobResponse

	FbAdsService interface {
		GetFbAdsJob(ctx context.Context, in *GetFbAdsJobRequest, opts ...grpc.CallOption) (*GetFbAdsJobResponse, error)
	}

	defaultFbAdsService struct {
		cli zrpc.Client
	}
)

func NewFbAdsService(cli zrpc.Client) FbAdsService {
	return &defaultFbAdsService{
		cli: cli,
	}
}

func (m *defaultFbAdsService) GetFbAdsJob(ctx context.Context, in *GetFbAdsJobRequest, opts ...grpc.CallOption) (*GetFbAdsJobResponse, error) {
	client := fbads.NewFbAdsServiceClient(m.cli.Conn())
	return client.GetFbAdsJob(ctx, in, opts...)
}
