// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2
// Source: fbads.proto

package server

import (
	"context"

	"github.com/hiepnv/crawl-ecomerce-golang/cmd/fb-ads-service/fbads"
	"github.com/hiepnv/crawl-ecomerce-golang/cmd/fb-ads-service/internal/logic"
	"github.com/hiepnv/crawl-ecomerce-golang/cmd/fb-ads-service/internal/svc"
)

type FbAdsServiceServer struct {
	svcCtx *svc.ServiceContext
	fbads.UnimplementedFbAdsServiceServer
}

func NewFbAdsServiceServer(svcCtx *svc.ServiceContext) *FbAdsServiceServer {
	return &FbAdsServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *FbAdsServiceServer) GetFbAdsJob(ctx context.Context, in *fbads.GetFbAdsJobRequest) (*fbads.GetFbAdsJobResponse, error) {
	l := logic.NewGetFbAdsJobLogic(ctx, s.svcCtx)
	return l.GetFbAdsJob(in)
}
