// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2

package types

type CreateAmazonJobRequest struct {
	Keyword  string   `json:"keyword,optional"`
	Urls     []string `json:"urls,optional"`
	Country  string   `json:"country,optional"`
	MaxItems int      `json:"max_items,optional"`
}

type CreateAmazonJobResponse struct {
	JobId string `json:"job_id"`
}

type CreateChina1688JobRequest struct {
	Keywords []string `json:"keywords,optional"`
	OfferIds []string `json:"offer_ids,optional"`
	MaxItems int      `json:"max_items,optional"`
}

type CreateChina1688JobResponse struct {
	JobId string `json:"job_id"`
}

type CreateFbAdsJobRequest struct {
	Query        string   `json:"query,optional"`
	PageId       string   `json:"page_id,optional"`
	Country      string   `json:"country,optional"`
	Category     string   `json:"category,optional"`
	MediaType    string   `json:"media_type,optional"`
	SortBy       string   `json:"sort_by,optional"`
	ActiveStatus string   `json:"active_status,optional"`
	MinDate      string   `json:"min_date,optional"`
	MaxDate      string   `json:"max_date,optional"`
	MaxItems     int      `json:"max_items,optional"`
	Advertisers  []string `json:"advertisers,optional"`
	FetchDetails bool     `json:"fetch_details,optional"`
}

type CreateFbAdsJobResponse struct {
	JobId string `json:"job_id"`
}

type CreateRedditJobRequest struct {
	Keyword string `json:"keyword"`
}

type CreateRedditJobResponse struct {
	JobId string `json:"job_id"`
}

type CreateTrendJobRequest struct {
	Keyword string `json:"keyword"`
	Geo     string `json:"geo,optional"`
}

type CreateTrendJobResponse struct {
	JobId string `json:"job_id"`
}

type GetAmazonJobRequest struct {
	Id string `path:"id"`
}

type GetAmazonJobResponse struct {
	Status       string `json:"status"`
	ProductCount int32  `json:"product_count"`
	AiOutput     string `json:"ai_output"`
}

type GetChina1688JobRequest struct {
	Id string `path:"id"`
}

type GetChina1688JobResponse struct {
	Status       string `json:"status"`
	ProductCount int32  `json:"product_count"`
	AiOutput     string `json:"ai_output"`
}

type GetFbAdsJobRequest struct {
	Id string `path:"id"`
}

type GetFbAdsJobResponse struct {
	Status   string `json:"status"`
	AdCount  int32  `json:"ad_count"`
	AiOutput string `json:"ai_output"`
}

type GetRedditJobRequest struct {
	Id string `path:"id"`
}

type GetRedditJobResponse struct {
	Status       string `json:"status"`
	PostCount    int32  `json:"post_count"`
	CommentCount int32  `json:"comment_count"`
	AiOutput     string `json:"ai_output"`
}

type GetTrendJobRequest struct {
	Id string `path:"id"`
}

type GetTrendJobResponse struct {
	Status   string `json:"status"`
	Keyword  string `json:"keyword"`
	AiOutput string `json:"ai_output"`
}
