// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2

package types

type CreateTrendJobRequest struct {
	Keyword string `json:"keyword"`
}

type CreateTrendJobResponse struct {
	JobId string `json:"job_id"`
}

type GetTrendJobRequest struct {
	Id string `path:"id"`
}

type GetTrendJobResponse struct {
	Status   string `json:"status"`
	Keyword  string `json:"keyword"`
	AiOutput string `json:"ai_output"`
}
