// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.27.3
// source: redditapi.proto

package redditapi

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RedditApiService_GetRedditApiJob_FullMethodName = "/redditapi.RedditApiService/GetRedditApiJob"
)

// RedditApiServiceClient is the client API for RedditApiService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RedditApiServiceClient interface {
	GetRedditApiJob(ctx context.Context, in *GetRedditApiJobRequest, opts ...grpc.CallOption) (*GetRedditApiJobResponse, error)
}

type redditApiServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRedditApiServiceClient(cc grpc.ClientConnInterface) RedditApiServiceClient {
	return &redditApiServiceClient{cc}
}

func (c *redditApiServiceClient) GetRedditApiJob(ctx context.Context, in *GetRedditApiJobRequest, opts ...grpc.CallOption) (*GetRedditApiJobResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRedditApiJobResponse)
	err := c.cc.Invoke(ctx, RedditApiService_GetRedditApiJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RedditApiServiceServer is the server API for RedditApiService service.
// All implementations must embed UnimplementedRedditApiServiceServer
// for forward compatibility.
type RedditApiServiceServer interface {
	GetRedditApiJob(context.Context, *GetRedditApiJobRequest) (*GetRedditApiJobResponse, error)
	mustEmbedUnimplementedRedditApiServiceServer()
}

// UnimplementedRedditApiServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRedditApiServiceServer struct{}

func (UnimplementedRedditApiServiceServer) GetRedditApiJob(context.Context, *GetRedditApiJobRequest) (*GetRedditApiJobResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRedditApiJob not implemented")
}
func (UnimplementedRedditApiServiceServer) mustEmbedUnimplementedRedditApiServiceServer() {}
func (UnimplementedRedditApiServiceServer) testEmbeddedByValue()                          {}

// UnsafeRedditApiServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RedditApiServiceServer will
// result in compilation errors.
type UnsafeRedditApiServiceServer interface {
	mustEmbedUnimplementedRedditApiServiceServer()
}

func RegisterRedditApiServiceServer(s grpc.ServiceRegistrar, srv RedditApiServiceServer) {
	// If the following call panics, it indicates UnimplementedRedditApiServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RedditApiService_ServiceDesc, srv)
}

func _RedditApiService_GetRedditApiJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRedditApiJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RedditApiServiceServer).GetRedditApiJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RedditApiService_GetRedditApiJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RedditApiServiceServer).GetRedditApiJob(ctx, req.(*GetRedditApiJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RedditApiService_ServiceDesc is the grpc.ServiceDesc for RedditApiService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RedditApiService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "redditapi.RedditApiService",
	HandlerType: (*RedditApiServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetRedditApiJob",
			Handler:    _RedditApiService_GetRedditApiJob_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "redditapi.proto",
}
