// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2
// Source: amazon.proto

package amazonservice

import (
	"context"

	"github.com/hiepnv/crawl-ecomerce-golang/cmd/amazon-service/amazon"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	GetAmazonJobRequest  = amazon.GetAmazonJobRequest
	GetAmazonJobResponse = amazon.GetAmazonJobResponse

	AmazonService interface {
		GetAmazonJob(ctx context.Context, in *GetAmazonJobRequest, opts ...grpc.CallOption) (*GetAmazonJobResponse, error)
	}

	defaultAmazonService struct {
		cli zrpc.Client
	}
)

func NewAmazonService(cli zrpc.Client) AmazonService {
	return &defaultAmazonService{
		cli: cli,
	}
}

func (m *defaultAmazonService) GetAmazonJob(ctx context.Context, in *GetAmazonJobRequest, opts ...grpc.CallOption) (*GetAmazonJobResponse, error) {
	client := amazon.NewAmazonServiceClient(m.cli.Conn())
	return client.GetAmazonJob(ctx, in, opts...)
}
