// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v5.27.3
// source: china1688.proto

package china1688

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetChina1688JobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChina1688JobRequest) Reset() {
	*x = GetChina1688JobRequest{}
	mi := &file_china1688_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChina1688JobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChina1688JobRequest) ProtoMessage() {}

func (x *GetChina1688JobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_china1688_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChina1688JobRequest.ProtoReflect.Descriptor instead.
func (*GetChina1688JobRequest) Descriptor() ([]byte, []int) {
	return file_china1688_proto_rawDescGZIP(), []int{0}
}

func (x *GetChina1688JobRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type GetChina1688JobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	ProductCount  int32                  `protobuf:"varint,2,opt,name=product_count,json=productCount,proto3" json:"product_count,omitempty"`
	AiOutput      string                 `protobuf:"bytes,3,opt,name=ai_output,json=aiOutput,proto3" json:"ai_output,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChina1688JobResponse) Reset() {
	*x = GetChina1688JobResponse{}
	mi := &file_china1688_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChina1688JobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChina1688JobResponse) ProtoMessage() {}

func (x *GetChina1688JobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_china1688_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChina1688JobResponse.ProtoReflect.Descriptor instead.
func (*GetChina1688JobResponse) Descriptor() ([]byte, []int) {
	return file_china1688_proto_rawDescGZIP(), []int{1}
}

func (x *GetChina1688JobResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetChina1688JobResponse) GetProductCount() int32 {
	if x != nil {
		return x.ProductCount
	}
	return 0
}

func (x *GetChina1688JobResponse) GetAiOutput() string {
	if x != nil {
		return x.AiOutput
	}
	return ""
}

var File_china1688_proto protoreflect.FileDescriptor

const file_china1688_proto_rawDesc = "" +
	"\n" +
	"\x0fchina1688.proto\x12\tchina1688\"/\n" +
	"\x16GetChina1688JobRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\"s\n" +
	"\x17GetChina1688JobResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12#\n" +
	"\rproduct_count\x18\x02 \x01(\x05R\fproductCount\x12\x1b\n" +
	"\tai_output\x18\x03 \x01(\tR\baiOutput2l\n" +
	"\x10China1688Service\x12X\n" +
	"\x0fGetChina1688Job\x12!.china1688.GetChina1688JobRequest\x1a\".china1688.GetChina1688JobResponseB\rZ\v./china1688b\x06proto3"

var (
	file_china1688_proto_rawDescOnce sync.Once
	file_china1688_proto_rawDescData []byte
)

func file_china1688_proto_rawDescGZIP() []byte {
	file_china1688_proto_rawDescOnce.Do(func() {
		file_china1688_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_china1688_proto_rawDesc), len(file_china1688_proto_rawDesc)))
	})
	return file_china1688_proto_rawDescData
}

var file_china1688_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_china1688_proto_goTypes = []any{
	(*GetChina1688JobRequest)(nil),  // 0: china1688.GetChina1688JobRequest
	(*GetChina1688JobResponse)(nil), // 1: china1688.GetChina1688JobResponse
}
var file_china1688_proto_depIdxs = []int32{
	0, // 0: china1688.China1688Service.GetChina1688Job:input_type -> china1688.GetChina1688JobRequest
	1, // 1: china1688.China1688Service.GetChina1688Job:output_type -> china1688.GetChina1688JobResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_china1688_proto_init() }
func file_china1688_proto_init() {
	if File_china1688_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_china1688_proto_rawDesc), len(file_china1688_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_china1688_proto_goTypes,
		DependencyIndexes: file_china1688_proto_depIdxs,
		MessageInfos:      file_china1688_proto_msgTypes,
	}.Build()
	File_china1688_proto = out.File
	file_china1688_proto_goTypes = nil
	file_china1688_proto_depIdxs = nil
}
