// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.27.3
// source: china1688.proto

package china1688

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	China1688Service_GetChina1688Job_FullMethodName = "/china1688.China1688Service/GetChina1688Job"
)

// China1688ServiceClient is the client API for China1688Service service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type China1688ServiceClient interface {
	GetChina1688Job(ctx context.Context, in *GetChina1688JobRequest, opts ...grpc.CallOption) (*GetChina1688JobResponse, error)
}

type china1688ServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewChina1688ServiceClient(cc grpc.ClientConnInterface) China1688ServiceClient {
	return &china1688ServiceClient{cc}
}

func (c *china1688ServiceClient) GetChina1688Job(ctx context.Context, in *GetChina1688JobRequest, opts ...grpc.CallOption) (*GetChina1688JobResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetChina1688JobResponse)
	err := c.cc.Invoke(ctx, China1688Service_GetChina1688Job_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// China1688ServiceServer is the server API for China1688Service service.
// All implementations must embed UnimplementedChina1688ServiceServer
// for forward compatibility.
type China1688ServiceServer interface {
	GetChina1688Job(context.Context, *GetChina1688JobRequest) (*GetChina1688JobResponse, error)
	mustEmbedUnimplementedChina1688ServiceServer()
}

// UnimplementedChina1688ServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedChina1688ServiceServer struct{}

func (UnimplementedChina1688ServiceServer) GetChina1688Job(context.Context, *GetChina1688JobRequest) (*GetChina1688JobResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetChina1688Job not implemented")
}
func (UnimplementedChina1688ServiceServer) mustEmbedUnimplementedChina1688ServiceServer() {}
func (UnimplementedChina1688ServiceServer) testEmbeddedByValue()                          {}

// UnsafeChina1688ServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to China1688ServiceServer will
// result in compilation errors.
type UnsafeChina1688ServiceServer interface {
	mustEmbedUnimplementedChina1688ServiceServer()
}

func RegisterChina1688ServiceServer(s grpc.ServiceRegistrar, srv China1688ServiceServer) {
	// If the following call panics, it indicates UnimplementedChina1688ServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&China1688Service_ServiceDesc, srv)
}

func _China1688Service_GetChina1688Job_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetChina1688JobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(China1688ServiceServer).GetChina1688Job(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: China1688Service_GetChina1688Job_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(China1688ServiceServer).GetChina1688Job(ctx, req.(*GetChina1688JobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// China1688Service_ServiceDesc is the grpc.ServiceDesc for China1688Service service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var China1688Service_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "china1688.China1688Service",
	HandlerType: (*China1688ServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetChina1688Job",
			Handler:    _China1688Service_GetChina1688Job_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "china1688.proto",
}
