// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2
// Source: china1688.proto

package server

import (
	"context"

	"github.com/hiepnv/crawl-ecomerce-golang/cmd/china1688-service/china1688"
	"github.com/hiepnv/crawl-ecomerce-golang/cmd/china1688-service/internal/logic"
	"github.com/hiepnv/crawl-ecomerce-golang/cmd/china1688-service/internal/svc"
)

type China1688ServiceServer struct {
	svcCtx *svc.ServiceContext
	china1688.UnimplementedChina1688ServiceServer
}

func NewChina1688ServiceServer(svcCtx *svc.ServiceContext) *China1688ServiceServer {
	return &China1688ServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *China1688ServiceServer) GetChina1688Job(ctx context.Context, in *china1688.GetChina1688JobRequest) (*china1688.GetChina1688JobResponse, error) {
	l := logic.NewGetChina1688JobLogic(ctx, s.svcCtx)
	return l.GetChina1688Job(in)
}
