// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v5.27.3
// source: trend.proto

package trend

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetTrendJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTrendJobRequest) Reset() {
	*x = GetTrendJobRequest{}
	mi := &file_trend_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTrendJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTrendJobRequest) ProtoMessage() {}

func (x *GetTrendJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_trend_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTrendJobRequest.ProtoReflect.Descriptor instead.
func (*GetTrendJobRequest) Descriptor() ([]byte, []int) {
	return file_trend_proto_rawDescGZIP(), []int{0}
}

func (x *GetTrendJobRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type TrendPointMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Date          string                 `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	Value         int32                  `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrendPointMsg) Reset() {
	*x = TrendPointMsg{}
	mi := &file_trend_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrendPointMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrendPointMsg) ProtoMessage() {}

func (x *TrendPointMsg) ProtoReflect() protoreflect.Message {
	mi := &file_trend_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrendPointMsg.ProtoReflect.Descriptor instead.
func (*TrendPointMsg) Descriptor() ([]byte, []int) {
	return file_trend_proto_rawDescGZIP(), []int{1}
}

func (x *TrendPointMsg) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *TrendPointMsg) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

type GetTrendJobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Keyword       string                 `protobuf:"bytes,2,opt,name=keyword,proto3" json:"keyword,omitempty"`
	Points        []*TrendPointMsg       `protobuf:"bytes,3,rep,name=points,proto3" json:"points,omitempty"`
	AiOutput      string                 `protobuf:"bytes,4,opt,name=ai_output,json=aiOutput,proto3" json:"ai_output,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTrendJobResponse) Reset() {
	*x = GetTrendJobResponse{}
	mi := &file_trend_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTrendJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTrendJobResponse) ProtoMessage() {}

func (x *GetTrendJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_trend_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTrendJobResponse.ProtoReflect.Descriptor instead.
func (*GetTrendJobResponse) Descriptor() ([]byte, []int) {
	return file_trend_proto_rawDescGZIP(), []int{2}
}

func (x *GetTrendJobResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetTrendJobResponse) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *GetTrendJobResponse) GetPoints() []*TrendPointMsg {
	if x != nil {
		return x.Points
	}
	return nil
}

func (x *GetTrendJobResponse) GetAiOutput() string {
	if x != nil {
		return x.AiOutput
	}
	return ""
}

var File_trend_proto protoreflect.FileDescriptor

const file_trend_proto_rawDesc = "" +
	"\n" +
	"\vtrend.proto\x12\x05trend\"+\n" +
	"\x12GetTrendJobRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\"9\n" +
	"\rTrendPointMsg\x12\x12\n" +
	"\x04date\x18\x01 \x01(\tR\x04date\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value\"\x92\x01\n" +
	"\x13GetTrendJobResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\akeyword\x18\x02 \x01(\tR\akeyword\x12,\n" +
	"\x06points\x18\x03 \x03(\v2\x14.trend.TrendPointMsgR\x06points\x12\x1b\n" +
	"\tai_output\x18\x04 \x01(\tR\baiOutput2T\n" +
	"\fTrendService\x12D\n" +
	"\vGetTrendJob\x12\x19.trend.GetTrendJobRequest\x1a\x1a.trend.GetTrendJobResponseB\tZ\a./trendb\x06proto3"

var (
	file_trend_proto_rawDescOnce sync.Once
	file_trend_proto_rawDescData []byte
)

func file_trend_proto_rawDescGZIP() []byte {
	file_trend_proto_rawDescOnce.Do(func() {
		file_trend_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_trend_proto_rawDesc), len(file_trend_proto_rawDesc)))
	})
	return file_trend_proto_rawDescData
}

var file_trend_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_trend_proto_goTypes = []any{
	(*GetTrendJobRequest)(nil),  // 0: trend.GetTrendJobRequest
	(*TrendPointMsg)(nil),       // 1: trend.TrendPointMsg
	(*GetTrendJobResponse)(nil), // 2: trend.GetTrendJobResponse
}
var file_trend_proto_depIdxs = []int32{
	1, // 0: trend.GetTrendJobResponse.points:type_name -> trend.TrendPointMsg
	0, // 1: trend.TrendService.GetTrendJob:input_type -> trend.GetTrendJobRequest
	2, // 2: trend.TrendService.GetTrendJob:output_type -> trend.GetTrendJobResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_trend_proto_init() }
func file_trend_proto_init() {
	if File_trend_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_trend_proto_rawDesc), len(file_trend_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_trend_proto_goTypes,
		DependencyIndexes: file_trend_proto_depIdxs,
		MessageInfos:      file_trend_proto_msgTypes,
	}.Build()
	File_trend_proto = out.File
	file_trend_proto_goTypes = nil
	file_trend_proto_depIdxs = nil
}
