// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.27.3
// source: trend.proto

package trend

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TrendService_GetTrendJob_FullMethodName = "/trend.TrendService/GetTrendJob"
)

// TrendServiceClient is the client API for TrendService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TrendServiceClient interface {
	GetTrendJob(ctx context.Context, in *GetTrendJobRequest, opts ...grpc.CallOption) (*GetTrendJobResponse, error)
}

type trendServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTrendServiceClient(cc grpc.ClientConnInterface) TrendServiceClient {
	return &trendServiceClient{cc}
}

func (c *trendServiceClient) GetTrendJob(ctx context.Context, in *GetTrendJobRequest, opts ...grpc.CallOption) (*GetTrendJobResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTrendJobResponse)
	err := c.cc.Invoke(ctx, TrendService_GetTrendJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TrendServiceServer is the server API for TrendService service.
// All implementations must embed UnimplementedTrendServiceServer
// for forward compatibility.
type TrendServiceServer interface {
	GetTrendJob(context.Context, *GetTrendJobRequest) (*GetTrendJobResponse, error)
	mustEmbedUnimplementedTrendServiceServer()
}

// UnimplementedTrendServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTrendServiceServer struct{}

func (UnimplementedTrendServiceServer) GetTrendJob(context.Context, *GetTrendJobRequest) (*GetTrendJobResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTrendJob not implemented")
}
func (UnimplementedTrendServiceServer) mustEmbedUnimplementedTrendServiceServer() {}
func (UnimplementedTrendServiceServer) testEmbeddedByValue()                      {}

// UnsafeTrendServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TrendServiceServer will
// result in compilation errors.
type UnsafeTrendServiceServer interface {
	mustEmbedUnimplementedTrendServiceServer()
}

func RegisterTrendServiceServer(s grpc.ServiceRegistrar, srv TrendServiceServer) {
	// If the following call panics, it indicates UnimplementedTrendServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TrendService_ServiceDesc, srv)
}

func _TrendService_GetTrendJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTrendJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrendServiceServer).GetTrendJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TrendService_GetTrendJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrendServiceServer).GetTrendJob(ctx, req.(*GetTrendJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TrendService_ServiceDesc is the grpc.ServiceDesc for TrendService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TrendService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "trend.TrendService",
	HandlerType: (*TrendServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetTrendJob",
			Handler:    _TrendService_GetTrendJob_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "trend.proto",
}
