// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2
// Source: redditapi.proto

package server

import (
	"context"

	"github.com/hiepnv/crawl-ecomerce-golang/cmd/reddit-api-service/internal/logic"
	"github.com/hiepnv/crawl-ecomerce-golang/cmd/reddit-api-service/internal/svc"
	"github.com/hiepnv/crawl-ecomerce-golang/cmd/reddit-api-service/redditapi"
)

type RedditApiServiceServer struct {
	svcCtx *svc.ServiceContext
	redditapi.UnimplementedRedditApiServiceServer
}

func NewRedditApiServiceServer(svcCtx *svc.ServiceContext) *RedditApiServiceServer {
	return &RedditApiServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *RedditApiServiceServer) GetRedditApiJob(ctx context.Context, in *redditapi.GetRedditApiJobRequest) (*redditapi.GetRedditApiJobResponse, error) {
	l := logic.NewGetRedditApiJobLogic(ctx, s.svcCtx)
	return l.GetRedditApiJob(in)
}
