// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v5.27.3
// source: reddit.proto

package reddit

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetRedditJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRedditJobRequest) Reset() {
	*x = GetRedditJobRequest{}
	mi := &file_reddit_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRedditJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRedditJobRequest) ProtoMessage() {}

func (x *GetRedditJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reddit_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRedditJobRequest.ProtoReflect.Descriptor instead.
func (*GetRedditJobRequest) Descriptor() ([]byte, []int) {
	return file_reddit_proto_rawDescGZIP(), []int{0}
}

func (x *GetRedditJobRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type GetRedditJobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	PostCount     int32                  `protobuf:"varint,2,opt,name=post_count,json=postCount,proto3" json:"post_count,omitempty"`
	CommentCount  int32                  `protobuf:"varint,3,opt,name=comment_count,json=commentCount,proto3" json:"comment_count,omitempty"`
	AiOutput      string                 `protobuf:"bytes,4,opt,name=ai_output,json=aiOutput,proto3" json:"ai_output,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRedditJobResponse) Reset() {
	*x = GetRedditJobResponse{}
	mi := &file_reddit_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRedditJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRedditJobResponse) ProtoMessage() {}

func (x *GetRedditJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_reddit_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRedditJobResponse.ProtoReflect.Descriptor instead.
func (*GetRedditJobResponse) Descriptor() ([]byte, []int) {
	return file_reddit_proto_rawDescGZIP(), []int{1}
}

func (x *GetRedditJobResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetRedditJobResponse) GetPostCount() int32 {
	if x != nil {
		return x.PostCount
	}
	return 0
}

func (x *GetRedditJobResponse) GetCommentCount() int32 {
	if x != nil {
		return x.CommentCount
	}
	return 0
}

func (x *GetRedditJobResponse) GetAiOutput() string {
	if x != nil {
		return x.AiOutput
	}
	return ""
}

var File_reddit_proto protoreflect.FileDescriptor

const file_reddit_proto_rawDesc = "" +
	"\n" +
	"\freddit.proto\x12\x06reddit\",\n" +
	"\x13GetRedditJobRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\"\x8f\x01\n" +
	"\x14GetRedditJobResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"post_count\x18\x02 \x01(\x05R\tpostCount\x12#\n" +
	"\rcomment_count\x18\x03 \x01(\x05R\fcommentCount\x12\x1b\n" +
	"\tai_output\x18\x04 \x01(\tR\baiOutput2Z\n" +
	"\rRedditService\x12I\n" +
	"\fGetRedditJob\x12\x1b.reddit.GetRedditJobRequest\x1a\x1c.reddit.GetRedditJobResponseB\n" +
	"Z\b./redditb\x06proto3"

var (
	file_reddit_proto_rawDescOnce sync.Once
	file_reddit_proto_rawDescData []byte
)

func file_reddit_proto_rawDescGZIP() []byte {
	file_reddit_proto_rawDescOnce.Do(func() {
		file_reddit_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_reddit_proto_rawDesc), len(file_reddit_proto_rawDesc)))
	})
	return file_reddit_proto_rawDescData
}

var file_reddit_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_reddit_proto_goTypes = []any{
	(*GetRedditJobRequest)(nil),  // 0: reddit.GetRedditJobRequest
	(*GetRedditJobResponse)(nil), // 1: reddit.GetRedditJobResponse
}
var file_reddit_proto_depIdxs = []int32{
	0, // 0: reddit.RedditService.GetRedditJob:input_type -> reddit.GetRedditJobRequest
	1, // 1: reddit.RedditService.GetRedditJob:output_type -> reddit.GetRedditJobResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_reddit_proto_init() }
func file_reddit_proto_init() {
	if File_reddit_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_reddit_proto_rawDesc), len(file_reddit_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_reddit_proto_goTypes,
		DependencyIndexes: file_reddit_proto_depIdxs,
		MessageInfos:      file_reddit_proto_msgTypes,
	}.Build()
	File_reddit_proto = out.File
	file_reddit_proto_goTypes = nil
	file_reddit_proto_depIdxs = nil
}
