// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.27.3
// source: reddit.proto

package reddit

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RedditService_GetRedditJob_FullMethodName = "/reddit.RedditService/GetRedditJob"
)

// RedditServiceClient is the client API for RedditService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RedditServiceClient interface {
	GetRedditJob(ctx context.Context, in *GetRedditJobRequest, opts ...grpc.CallOption) (*GetRedditJobResponse, error)
}

type redditServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRedditServiceClient(cc grpc.ClientConnInterface) RedditServiceClient {
	return &redditServiceClient{cc}
}

func (c *redditServiceClient) GetRedditJob(ctx context.Context, in *GetRedditJobRequest, opts ...grpc.CallOption) (*GetRedditJobResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRedditJobResponse)
	err := c.cc.Invoke(ctx, RedditService_GetRedditJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RedditServiceServer is the server API for RedditService service.
// All implementations must embed UnimplementedRedditServiceServer
// for forward compatibility.
type RedditServiceServer interface {
	GetRedditJob(context.Context, *GetRedditJobRequest) (*GetRedditJobResponse, error)
	mustEmbedUnimplementedRedditServiceServer()
}

// UnimplementedRedditServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRedditServiceServer struct{}

func (UnimplementedRedditServiceServer) GetRedditJob(context.Context, *GetRedditJobRequest) (*GetRedditJobResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRedditJob not implemented")
}
func (UnimplementedRedditServiceServer) mustEmbedUnimplementedRedditServiceServer() {}
func (UnimplementedRedditServiceServer) testEmbeddedByValue()                       {}

// UnsafeRedditServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RedditServiceServer will
// result in compilation errors.
type UnsafeRedditServiceServer interface {
	mustEmbedUnimplementedRedditServiceServer()
}

func RegisterRedditServiceServer(s grpc.ServiceRegistrar, srv RedditServiceServer) {
	// If the following call panics, it indicates UnimplementedRedditServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RedditService_ServiceDesc, srv)
}

func _RedditService_GetRedditJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRedditJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RedditServiceServer).GetRedditJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RedditService_GetRedditJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RedditServiceServer).GetRedditJob(ctx, req.(*GetRedditJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RedditService_ServiceDesc is the grpc.ServiceDesc for RedditService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RedditService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "reddit.RedditService",
	HandlerType: (*RedditServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetRedditJob",
			Handler:    _RedditService_GetRedditJob_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "reddit.proto",
}
