// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2
// Source: trend.proto

package trendservice

import (
	"context"

	"github.com/hiepnv/crawl-ecomerce-golang/cmd/trend-service/trend"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	GetTrendJobRequest  = trend.GetTrendJobRequest
	GetTrendJobResponse = trend.GetTrendJobResponse
	TrendPointMsg       = trend.TrendPointMsg

	TrendService interface {
		GetTrendJob(ctx context.Context, in *GetTrendJobRequest, opts ...grpc.CallOption) (*GetTrendJobResponse, error)
	}

	defaultTrendService struct {
		cli zrpc.Client
	}
)

func NewTrendService(cli zrpc.Client) TrendService {
	return &defaultTrendService{
		cli: cli,
	}
}

func (m *defaultTrendService) GetTrendJob(ctx context.Context, in *GetTrendJobRequest, opts ...grpc.CallOption) (*GetTrendJobResponse, error) {
	client := trend.NewTrendServiceClient(m.cli.Conn())
	return client.GetTrendJob(ctx, in, opts...)
}
