// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2

package handler

import (
	"net/http"

	"github.com/hiepnv/crawl-ecomerce-golang/cmd/api-gateway/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/jobs/amazon",
				Handler: CreateAmazonJobHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/jobs/amazon/:id",
				Handler: GetAmazonJobHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/jobs/china1688",
				Handler: CreateChina1688JobHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/jobs/china1688/:id",
				Handler: GetChina1688JobHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/jobs/fbads",
				Handler: CreateFbAdsJobHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/jobs/fbads/:id",
				Handler: GetFbAdsJobHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/jobs/reddit",
				Handler: CreateRedditJobHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/jobs/reddit-api",
				Handler: CreateRedditApiJobHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/jobs/reddit-api/:id",
				Handler: GetRedditApiJobHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/jobs/reddit/:id",
				Handler: GetRedditJobHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/jobs/trend",
				Handler: CreateTrendJobHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/jobs/trend/:id",
				Handler: GetTrendJobHandler(serverCtx),
			},
		},
	)
}
