// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2

package handler

import (
	"net/http"

	"github.com/hiepnv/crawl-ecomerce-golang/cmd/api-gateway/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/jobs/trend",
				Handler: CreateTrendJobHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/jobs/trend/:id",
				Handler: GetTrendJobHandler(serverCtx),
			},
		},
	)
}
