// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2
// Source: reddit.proto

package server

import (
	"context"

	"github.com/hiepnv/crawl-ecomerce-golang/cmd/reddit-service/internal/logic"
	"github.com/hiepnv/crawl-ecomerce-golang/cmd/reddit-service/internal/svc"
	"github.com/hiepnv/crawl-ecomerce-golang/cmd/reddit-service/reddit"
)

type RedditServiceServer struct {
	svcCtx *svc.ServiceContext
	reddit.UnimplementedRedditServiceServer
}

func NewRedditServiceServer(svcCtx *svc.ServiceContext) *RedditServiceServer {
	return &RedditServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *RedditServiceServer) GetRedditJob(ctx context.Context, in *reddit.GetRedditJobRequest) (*reddit.GetRedditJobResponse, error) {
	l := logic.NewGetRedditJobLogic(ctx, s.svcCtx)
	return l.GetRedditJob(in)
}
