// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.27.3
// source: rpc/amazon/amazon.proto

package amazon

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AmazonService_GetAmazonJob_FullMethodName = "/amazon.AmazonService/GetAmazonJob"
)

// AmazonServiceClient is the client API for AmazonService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AmazonServiceClient interface {
	GetAmazonJob(ctx context.Context, in *GetAmazonJobRequest, opts ...grpc.CallOption) (*GetAmazonJobResponse, error)
}

type amazonServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAmazonServiceClient(cc grpc.ClientConnInterface) AmazonServiceClient {
	return &amazonServiceClient{cc}
}

func (c *amazonServiceClient) GetAmazonJob(ctx context.Context, in *GetAmazonJobRequest, opts ...grpc.CallOption) (*GetAmazonJobResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAmazonJobResponse)
	err := c.cc.Invoke(ctx, AmazonService_GetAmazonJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AmazonServiceServer is the server API for AmazonService service.
// All implementations must embed UnimplementedAmazonServiceServer
// for forward compatibility.
type AmazonServiceServer interface {
	GetAmazonJob(context.Context, *GetAmazonJobRequest) (*GetAmazonJobResponse, error)
	mustEmbedUnimplementedAmazonServiceServer()
}

// UnimplementedAmazonServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAmazonServiceServer struct{}

func (UnimplementedAmazonServiceServer) GetAmazonJob(context.Context, *GetAmazonJobRequest) (*GetAmazonJobResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAmazonJob not implemented")
}
func (UnimplementedAmazonServiceServer) mustEmbedUnimplementedAmazonServiceServer() {}
func (UnimplementedAmazonServiceServer) testEmbeddedByValue()                       {}

// UnsafeAmazonServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AmazonServiceServer will
// result in compilation errors.
type UnsafeAmazonServiceServer interface {
	mustEmbedUnimplementedAmazonServiceServer()
}

func RegisterAmazonServiceServer(s grpc.ServiceRegistrar, srv AmazonServiceServer) {
	// If the following call panics, it indicates UnimplementedAmazonServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AmazonService_ServiceDesc, srv)
}

func _AmazonService_GetAmazonJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAmazonJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AmazonServiceServer).GetAmazonJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AmazonService_GetAmazonJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AmazonServiceServer).GetAmazonJob(ctx, req.(*GetAmazonJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AmazonService_ServiceDesc is the grpc.ServiceDesc for AmazonService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AmazonService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "amazon.AmazonService",
	HandlerType: (*AmazonServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAmazonJob",
			Handler:    _AmazonService_GetAmazonJob_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rpc/amazon/amazon.proto",
}
