// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v5.27.3
// source: rpc/amazon/amazon.proto

package amazon

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetAmazonJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAmazonJobRequest) Reset() {
	*x = GetAmazonJobRequest{}
	mi := &file_rpc_amazon_amazon_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAmazonJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAmazonJobRequest) ProtoMessage() {}

func (x *GetAmazonJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_amazon_amazon_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAmazonJobRequest.ProtoReflect.Descriptor instead.
func (*GetAmazonJobRequest) Descriptor() ([]byte, []int) {
	return file_rpc_amazon_amazon_proto_rawDescGZIP(), []int{0}
}

func (x *GetAmazonJobRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type GetAmazonJobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	ProductCount  int32                  `protobuf:"varint,2,opt,name=product_count,json=productCount,proto3" json:"product_count,omitempty"`
	AiOutput      string                 `protobuf:"bytes,3,opt,name=ai_output,json=aiOutput,proto3" json:"ai_output,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAmazonJobResponse) Reset() {
	*x = GetAmazonJobResponse{}
	mi := &file_rpc_amazon_amazon_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAmazonJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAmazonJobResponse) ProtoMessage() {}

func (x *GetAmazonJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_amazon_amazon_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAmazonJobResponse.ProtoReflect.Descriptor instead.
func (*GetAmazonJobResponse) Descriptor() ([]byte, []int) {
	return file_rpc_amazon_amazon_proto_rawDescGZIP(), []int{1}
}

func (x *GetAmazonJobResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetAmazonJobResponse) GetProductCount() int32 {
	if x != nil {
		return x.ProductCount
	}
	return 0
}

func (x *GetAmazonJobResponse) GetAiOutput() string {
	if x != nil {
		return x.AiOutput
	}
	return ""
}

var File_rpc_amazon_amazon_proto protoreflect.FileDescriptor

const file_rpc_amazon_amazon_proto_rawDesc = "" +
	"\n" +
	"\x17rpc/amazon/amazon.proto\x12\x06amazon\",\n" +
	"\x13GetAmazonJobRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\"p\n" +
	"\x14GetAmazonJobResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12#\n" +
	"\rproduct_count\x18\x02 \x01(\x05R\fproductCount\x12\x1b\n" +
	"\tai_output\x18\x03 \x01(\tR\baiOutput2Z\n" +
	"\rAmazonService\x12I\n" +
	"\fGetAmazonJob\x12\x1b.amazon.GetAmazonJobRequest\x1a\x1c.amazon.GetAmazonJobResponseB\n" +
	"Z\b./amazonb\x06proto3"

var (
	file_rpc_amazon_amazon_proto_rawDescOnce sync.Once
	file_rpc_amazon_amazon_proto_rawDescData []byte
)

func file_rpc_amazon_amazon_proto_rawDescGZIP() []byte {
	file_rpc_amazon_amazon_proto_rawDescOnce.Do(func() {
		file_rpc_amazon_amazon_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpc_amazon_amazon_proto_rawDesc), len(file_rpc_amazon_amazon_proto_rawDesc)))
	})
	return file_rpc_amazon_amazon_proto_rawDescData
}

var file_rpc_amazon_amazon_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_rpc_amazon_amazon_proto_goTypes = []any{
	(*GetAmazonJobRequest)(nil),  // 0: amazon.GetAmazonJobRequest
	(*GetAmazonJobResponse)(nil), // 1: amazon.GetAmazonJobResponse
}
var file_rpc_amazon_amazon_proto_depIdxs = []int32{
	0, // 0: amazon.AmazonService.GetAmazonJob:input_type -> amazon.GetAmazonJobRequest
	1, // 1: amazon.AmazonService.GetAmazonJob:output_type -> amazon.GetAmazonJobResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_rpc_amazon_amazon_proto_init() }
func file_rpc_amazon_amazon_proto_init() {
	if File_rpc_amazon_amazon_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_amazon_amazon_proto_rawDesc), len(file_rpc_amazon_amazon_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rpc_amazon_amazon_proto_goTypes,
		DependencyIndexes: file_rpc_amazon_amazon_proto_depIdxs,
		MessageInfos:      file_rpc_amazon_amazon_proto_msgTypes,
	}.Build()
	File_rpc_amazon_amazon_proto = out.File
	file_rpc_amazon_amazon_proto_goTypes = nil
	file_rpc_amazon_amazon_proto_depIdxs = nil
}
