// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2
// Source: amazon.proto

package server

import (
	"context"

	"github.com/hiepnv/crawl-ecomerce-golang/cmd/amazon-service/amazon"
	"github.com/hiepnv/crawl-ecomerce-golang/cmd/amazon-service/internal/logic"
	"github.com/hiepnv/crawl-ecomerce-golang/cmd/amazon-service/internal/svc"
)

type AmazonServiceServer struct {
	svcCtx *svc.ServiceContext
	amazon.UnimplementedAmazonServiceServer
}

func NewAmazonServiceServer(svcCtx *svc.ServiceContext) *AmazonServiceServer {
	return &AmazonServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *AmazonServiceServer) GetAmazonJob(ctx context.Context, in *amazon.GetAmazonJobRequest) (*amazon.GetAmazonJobResponse, error) {
	l := logic.NewGetAmazonJobLogic(ctx, s.svcCtx)
	return l.GetAmazonJob(in)
}
